title: Carlos Li Zheming # your name (or website title) here
logo: "/images/New_Profile_size_small.jpg?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  <b>Data Analyst Trainee</b><br>
  @NTUC LearningHub<br>
  under SGUnited Skills Programme<br>
  (a training programme founded by Singapore Government)
  <br><br>
  <b>Bachelor of Engineering</b>
  <br><br>
  <b>Skills</b>:<br>
  Machine Learning, Python, Power BI, SQL, Power Query, Excel, PowerPoint, Word
  <br><br>


  <a href="https://www.linkedin.com/in/lizheming/">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
